### ISSUE TITLE
offer promise api

### ISSUE THREAD

**Issue by capaj** [ceejbot/recurring#46]
most libraries today offer both callback and promise api. It would be great if recurring could offer the same for it's consumers.

**Comment by mrfelton** [comment]
Quick way:

```
var recurly = Promise.promisifyAll(new recurring());
```
https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object

**Comment by capaj** [comment]
@mrfelton I don't think that will work

**Comment by mrfelton** [comment]
We use it @capaj

**Comment by capaj** [comment]
@mrfelton I thought that promisifyAll goes through object properties and creates 'async' version for each.

when I do what you propose I end up with:
```
recurring Recurring {
  AUTH_BASIC: undefined,
  AccountAsync: [Function],
  AddonAsync: [Function],
  AdjustmentAsync: [Function],
  BillingInfoAsync: [Function],
  CouponAsync: [Function],
  InvoiceAsync: [Function],
  PlanAsync: [Function],
  RedemptionAsync: [Function],
  SubscriptionAsync: [Function],
  TransactionAsync: [Function],
  FormResponseTokenAsync: [Function],
  setAPIKeyAsync: [Function],
  setRateLimitAsync: [Function] }


```

you probably meant to promisify all of these properties individually, right?

**Comment by mrfelton** [comment]
@capaj the latest version now fully supports promises.
