### ISSUE TITLE
Listing this project on the Recurly Dev site

### ISSUE THREAD

**Issue by bhelx** [ceejbot/recurring#72]
Hey Everyone,

First off I just want to say thank you for building and maintaining this library. I know from experience that it takes a lot of time and persistence to keep an open source project like this moving.

In 2016 I [added this user agent](https://github.com/ceejbot/recurring/commit/209501479c0e7eee24d808101d5c402c82f9ab79#diff-9abfff17df8cb4b40a148d31eb093cb3) so we could track who is using this library. Since then, it's been adopted by a good portion of our node users. We've also been impressed with the responsiveness in which y'all deal with issues.

On Recurly's dev documentation site, we have this project listed as the unofficial node library: https://github.com/cgerrior/node-recurly

It's in a pretty bad state and I'd like to switch that link over to your project. I just wanted to come here to ask if that's okay. We unfortunately can't officially support the library at this time, but I also wanted to see if there is anything that I (or Recurly) can do to help out.

Thanks Again!

**Comment by mrfelton** [comment]
Hi,

Thanks for reaching out. We’d be thrilled to have this project listed as the official recommendation by Recurly. We use this library extensively within our own software and try our best to keep it well maintained. I don’t think there is anything that we need from you guys at this time, but if that changes in the future we’ll be sure to reach out!

Cheers,
- Tom


--
Tom Kirkpatrick
Founder & CTO, KirkDesigns
+34 (0) 681 395 967 | Skype: tkirkpatrick99

**Comment by bhelx** [comment]
Okay, the link on http://dev.recurly.com/ now points to this project.
